### PR TITLE
Fix helper to produce correct path to chef-zero binary at /opt/chef/embe...

### PR DESCRIPTION
**Pull request by stephenlauck**
...dded/bin/chef-zero

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey there! What's up? Any ideas on the test failure?

**Comment by stephenlauck** [comment]
Nope, but I'll check it out and fix. Let's go to lunch soon @sethvargo !

**Comment by sethvargo** [comment]
Sounds good! Hmu on Facebook :smile:

**Comment by stephenlauck** [comment]
@sethvargo fixed, but I changed which rubies to test on, not sure what I really want in terms of versions.

**Comment by sethvargo** [comment]
Good enough for me :smie

**Pull request merged**
